#!/usr/bin/env bash
dir=$(rlink "${1:-.}")
cd "$dir"
if ! git diff-index HEAD --exit-code >/dev/null; then
  print-big-warning "You have uncommitted changes in $dir"
elif [ $(git rev-parse --abbrev-ref HEAD) = master ]; then
  if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/master)" ]; then
    print-big-warning "Local master is out of sync with origin/master in $dir"
  fi
fi
