#!/usr/bin/env bash
dir=$(rlink "${1:-.}")
cd "$dir"
echo "Checking git state in $(pwd)"
if ! git status | grep -q 'working tree clean'; then
  git diff-index HEAD --exit-code
  print-big-warning "You have uncommitted changes in $dir"
elif [ $(git rev-parse --abbrev-ref HEAD) = master ] &&
     [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/master)" ]; then
  print-big-warning "Local master is out of sync with origin/master in $dir"
else
  if-verbose echo "$(basename $(pwd)) has a clean status"
fi
