#!/usr/bin/env bash
dir=$(rlink "${1:-.}")
cd "$dir"
if ! git diff-index --quiet HEAD; then
  echo -ne '\033[0;33m'
  echo "##################################################################"
  echo "## You have uncommitted changes in $dir"
  echo "##################################################################"
  echo -ne '\033[0m'
elif [ $(cur) = master ]; then
  if [ "$(curcommit)" != "$(grp origin/master)" ]; then
    echo -ne '\033[0;33m'
    echo "##################################################################"
    echo "## Local master is out of sync with origin/master in $dir"
    echo "##################################################################"
    echo -ne '\033[0m'
  fi
fi
