#!/usr/bin/env python3
import sys, os

if len(sys.argv) != 3:
    print("Need exactly two arguments")
    sys.exit(1)

in_filename = sys.argv[1]
out_filename = sys.argv[2]

if not os.path.isfile(in_filename):
    print(in_filename, "does not exist")
    sys.exit(1)

if os.path.splitext(out_filename)[1] != ".srt":
    out_filename = os.path.splitext(out_filename)[0] + ".srt"

if os.path.isfile(out_filename):
    print(out_filename, "already exists")
    sys.exit(1)

with open(in_filename, 'r', encoding='windows-1251') as file:
    contents = file.read()

with open(out_filename, 'w') as file:
    file.write(contents)

print("Converted", in_filename, "to", out_filename)
