#!/usr/bin/env python3
import sys, os

print(sys.argv)
if len(sys.argv) != 3:
    print("Need exactly two arguments")
    sys.exit(1)

in_filename = sys.argv[1]
out_filename = sys.argv[2]

if not os.path.isfile(in_filename):
    print(filename, "does not exist")
    sys.exit(1)

if os.path.isfile(out_filename):
    print(filename, "already exists")
    sys.exit(1)

with open(in_filename, 'r', encoding='windows-1251') as file:
    contents = file.read()

with open(out_filename, 'w') as file:
    file.write(contents)

print("Converted", in_filename, "to", out_filename)
