#!/usr/bin/env bash

NAME="$1"

echo "Regular:"
rg "$NAME" "node_modules/@draftbit/re-font-awesome/src/Regular.re" || echo "(none)"

echo "Brands:"
rg "$NAME" "node_modules/@draftbit/re-font-awesome/src/Brands.re" || echo "(none)"
