#!/usr/bin/env bash

NAME="$1"

FA_DIR=~/workspace/draftbit/draftbit/builder/node_modules/@draftbit/re-font-awesome/src

echo "Regular:"
rg "$NAME" "$FA_DIR/Regular.re" || echo "(none)"

echo "Brands:"
rg "$NAME" "$FA_DIR/Brands.re" || echo "(none)"
