#!/usr/bin/env bash

git status | rg 'modified:|new file:' | rg '\.(t|j)sx?$' | sd '(both )?modified:|new file:' '' | xargs yarn prettier --write

git status | rg 'renamed:' | rg '\.(t|j)sx?$' | sd 'renamed:.* \->(.*)' '$1' | xargs yarn prettier --write
