#!/usr/bin/env bash

git status | rg 'modified:|new file:' | rg '\.res$' | sd 'modified:|new file:' '' | xargs format-rescript.js

git status | rg 'renamed:' | rg '\.res$' | sd 'renamed:.* \->(.*)' '$1' | xargs format-rescript.js
