#!/usr/bin/env bash

scriptname="rg-replace"
old=$1
new=$2
flags="$3"

if [[ $# -lt 2 ]]; then
  echo "Usage: $scriptname <old string> <new string>"
  exit 1
fi

rg -l $flags "$old" | xargs sd "$old" "$new"
